### ISSUE TITLE
dropped packet with RIOT native destination 1?

### ISSUE THREAD

**Issue by Lotterleben** [sgso/marz#1]
Hi,
thank you for creating this application, I think it will be very useful to me!
However, I'm trying to figure out how to actually get packets through to my RIOT instance via marz (i.e. which address & port I have to use and how), using netcat (for now), and I've gotten marz to react to

    echo "foo" | nc -6u fe80::ff:fe00:b57 5683

(with the default config), but all I'm getting from marz is the answer

    [UDP6 5683] Received 4 data bytes from ('::1', 57820): Relaying through 57820 to RiotEndpoint(hwaddr=1, ipv6='fe80::ff:fe00:1', port=5683)
    dropped packet with RIOT native destination 1

This must be caused by marz.c:152 failing, but i just don't get what caused that. Could you maybe tell me what I'm doing wrong here? :)

**Comment by sgso** [comment]
Hey,
I had to try this myself:
`recipient` in the config blog is the decimal representation of the transceiver address. Its default is 1 because in older versions of RIOT you could do:
`./bin/native/application.elf tap1 -i 1`
and the native platform would configure itself with the transceiver address 1. Then somebody last year decided to change it so that the `-i` parameter would not generate the transceiver address directly but instead feed that value to some determinstic (maybe only on one machine/user/who knows) algorithm that generates the transceiver address. The immediate work-around was, to put a negative value there which would trigger the old behaviour. But this doesn't seem to work anymore. But you can just query that address manually with the `addr` command in any shell enabled application. So when I use `-i 1` on the latest RIOT version you can type  `addr` in a shell enabled platform and get something like this:
`[transceiver] got address: 8960`
 Once you know that value, you're set. For example with the coap-plugtests example application that I tested it with I do:
```
λ ./bin/native/coap-plugtests.elf tap1 -i 1
> ifconfig
ifconfig
Iface   0   HWaddr: 0x2300 Channel: 0 PAN ID: 0xabcd
            EUI-64: 00-00-00-ff-fe-00-23-00
            Source address mode: short
            Transceivers:
             * native
            inet6 addr: fe80::ff:fe00:2300/128  scope: local
            inet6 addr: ff02::1:ff00:2300/128  scope: local [multicast]
            inet6 addr: ff02::1/128  scope: local [multicast]
```
The 0x2300 is the hex value of the number I get from `addr`. The resulting inet6 addr is `fe80::ff:fe00:2300`. To reach this application I can fill `8960` as the `recipient` and sucessfully do a CoAP ping:
`λ echo "400100FF" | xxd -r -p  | nc -6u localhost 5683`
which shows me a reaction in the native shell, a log by marz
`[UDP6 5683] Received 4 data bytes from ('::1', 52917): Relaying through 52917 to RiotEndpoint(hwaddr=8960, ipv6='fe80::ff:fe00:2300', port=5683)`
and Wireshark confirms this as well (when you use Wireshark, get the RIOT protocol dissector from the tools directory and don't get confused by RIOTs UDP source port, which is always 192)

**Comment by Lotterleben** [comment]
That helped so much, thanks! :) :+1:
